[dev]
  targetPort = 8080

[[edge_functions]]
  path = "/*"
  function = "page-meta"
  # excludedPath = ["/", "/assets/*", "/*.js", "/*.css", "/*.txt", "/*.png", "/*.ico", "/*.jpeg", "/*.jpg", "/*.webmanifest"]
  cache = "manual"
