[dev]
 framework = "#static"
 publish = "dist"
 [dev.https]
   certFile = ".cert/cert.pem"
   keyFile = ".cert/key.pem"

[[edge_functions]]
  path = "/*"
  function = "page-meta"
  excludedPath = ["/", "/assets/*", "/*.js", "/*.css", "/*.txt", "/*.xml", "/*.png", "/*.ico", "/*.jpeg", "/*.jpg", "/*.webmanifest"]
  cache = "manual"
